--- 
- name: install LAMP + Wordpress 
  hosts: all
  become: yes
  vars:
    wp_mysql_db: wordpress
    wp_mysql_user: dbuser
    wp_mysql_password: dbpass
    wp_mysql_host: localhost
    mysql_root_password: passwd
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: upgrade all packages
    yum:
      name: "*"
      state: latest
  - name: Install epel repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present 
  - name: Install remi repo
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present
  - name: install yum-utils
    yum: 
      name: yum-utils 
      state: latest
  - name: install php7.2
    command: "sudo amazon-linux-extras install -y php7.2" 
  - name: install MySQL-python
    yum: 
      name: MySQL-python 
      state: present
  - name: install mariadb
    yum: 
      name:
        - mariadb-server 
        - mariadb
      state: latest
  - name: Starting mariadb
    service:
     name: mariadb
     state: started
     enabled: true
  - name: Starting httpd
    service:
     name: httpd
     state: started
     enabled: true
  - name: Remove httpd welcome page
    file:
      path: "/etc/httpd/conf.d/welcome.conf"
      state: absent
  - name: Download & unpack wordpress
    unarchive:
      src: http://www.wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
  - name: Rename sample wordpress configuration
    command: "mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php"    
  - name: Update WordPress config file
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp={{ item.regexp }} line={{ item.line }}
    with_items:
      - {'regexp': "define\\( 'DB_NAME', '(database_name_here)+' \\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
      - {'regexp': "define\\( 'DB_USER', '(username_here)+' \\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
      - {'regexp': "define\\( 'DB_PASSWORD', '(password_here)+' \\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
      - {'regexp': "define\\( 'DB_HOST', '(localhost)+' \\);", 'line': "define('DB_HOST', '{{wp_mysql_host}}');"}
  - name: Update default Apache site
    lineinfile:
     dest=/etc/httpd/conf/httpd.conf
     line="DocumentRoot /var/www/html/wordpress"
  - name: update mysql root password for all root accounts
    mysql_user: 
       name: root 
       host: "{{ item }}" 
       password: "{{ mysql_root_password }}"
       login_user: root
       login_password: "{{ mysql_root_password }}"
       check_implicit_admin: yes
       priv: "*.*:ALL,GRANT"
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
  - name: copy .my.cnf file with root password credentials
    template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  - name: delete anonymous MySQL server user for server
    action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
  - name: delete anonymous MySQL server user for localhost
    action: mysql_user user="" state="absent"
  - name: remove the MySQL test database
    action: mysql_db db=test state=absent      
  - name: Creating database for wordpress
    mysql_db:
      name: "{{ wp_mysql_db }}"
      state: present
  - name: Creating user for wordpress and allow all permissions to db wordpress
    mysql_user:
      name: "{{ wp_mysql_user }}"
      password: "{{wp_mysql_password}}"
      priv: "{{ wp_mysql_db }}.*:ALL"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
  - name: restarting httpd and mysqld
    service: name={{ item }} state=restarted
    with_items:
     - httpd
     - mariadb            
